name: Build imagemagick
on:
  workflow_dispatch:
    inputs:
      php:
        description: PHP version to build for
        required: true
      tag:
        description: ImageMagick tag
        required: true
defaults:
  run:
    shell: cmd
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          arch: [x64, x86]
    runs-on: windows-2022
    steps:
      - name: Checkout winlib-builder
        uses: actions/checkout@v5
        with:
          path: winlib-builder
      - name: Checkout ImageMagick/Windows
        uses: actions/checkout@v5
        with:
          path: Windows
          repository: ImageMagick/Windows.git
          ref: main
      - name: Checkout ImageMagick
        uses: actions/checkout@v5
        with:
          path: Windows\ImageMagick
          repository: ImageMagick/ImageMagick.git
          ref: ${{ inputs.tag }}
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      - name: Compute virtual inputs
        id: virtuals
        run: powershell winlib-builder/scripts/compute-virtuals -version ${{github.event.inputs.php}} -arch ${{matrix.arch}} -SkipToolsetCheck
      - name: Add missing vs components
        if: ${{ steps.virtuals.outputs.vsnum != '17' }}
        shell: pwsh
        run: powershell winlib-builder/scripts/add-vs-components ${{ steps.virtuals.outputs.vsnum }} -AddATL -AddMFC
      - name: Fetch dependencies
        run: cd Windows && clone-repositories-im7.cmd
      - name: Patch imagemagick
        run: |
          cd Windows\Configure && git apply --ignore-whitespace ..\..\winlib-builder\patches\imagemagick.patch && cd ..\..
          if "${{steps.virtuals.outputs.vsnum}}" neq "17" (
            cd Windows\Imagemagick && git apply --ignore-whitespace ..\..\winlib-builder\patches\imagemagick-ma.patch
            git apply --ignore-whitespace ..\..\winlib-builder\patches\imagemagick-emf.patch
          )
      - name: Configure imagemagick
        run: |
          cd Windows\Configure
          if "${{steps.virtuals.outputs.vsnum}}" neq "15" (
            msbuild /p:Configuration=Release,Platform=${{matrix.arch}},PlatformToolset=${{steps.virtuals.outputs.msts}} configure.sln
          ) else (
            msbuild /p:Configuration=Release,Platform=${{matrix.arch}},PlatformToolset=${{steps.virtuals.outputs.msts}},WindowsTargetPlatformVersion=${{steps.virtuals.outputs.winsdk}} configure.sln
          )
          cp Artifacts\Release\${{matrix.arch}}\bin\Configure.Release.${{matrix.arch}}.exe configure.exe
          start /wait configure /noWizard /${{matrix.arch}} /noHdri /noOpenCL /deprecated /VS${{steps.virtuals.outputs.vsyear}}
      - name: Build imagemagick
        run: |
          cd Windows
          msbuild /p:Configuration=Release,Platform=${{matrix.arch}},PlatformToolset=${{steps.virtuals.outputs.msts}} IM7.Dynamic.${{ matrix.arch }}.sln
      - name: Install imagemagick
        run: |
          cd Windows\Artifacts
          xcopy bin\* ..\..\install\bin\*
          del ..\..\install\bin\CORE_RL_aom_.pdb
          del ..\..\install\bin\CORE_RL_brotli_.pdb
          del ..\..\install\bin\CORE_RL_croco_.pdb
          del ..\..\install\bin\CORE_RL_ffi_.pdb
          del ..\..\install\bin\CORE_RL_highway_.pdb
          del ..\..\install\bin\CORE_RL_libde265_.pdb
          del ..\..\install\bin\CORE_RL_pixman_.pdb
          del ..\..\install\bin\CORE_RL_raqm_.pdb
          del ..\..\install\bin\*fuzzer.pdb
          xcopy ..\ImageMagick\MagickCore\*.h ..\..\install\include\MagickCore\*
          del ..\..\install\include\MagickCore\*-private.h
          xcopy ..\ImageMagick\MagickWand\*.h ..\..\install\include\MagickWand\*
          del ..\..\install\include\MagickWand\*-private.h
          xcopy lib\*.lib ..\..\install\lib\*
          xcopy lib\*.exp ..\..\install\lib\*
          xcopy lib\*.pdb ..\..\install\lib\*
          del ..\..\install\lib\CORE_RL_aom_.pdb
          del ..\..\install\lib\CORE_RL_brotli_.pdb
          del ..\..\install\lib\CORE_RL_croco_.pdb
          del ..\..\install\lib\CORE_RL_ffi_.pdb
          del ..\..\install\lib\CORE_RL_highway_.pdb
          del ..\..\install\lib\CORE_RL_libde265_.pdb
          del ..\..\install\lib\CORE_RL_pixman_.pdb
          del ..\..\install\lib\CORE_RL_raqm_.pdb
          xcopy ..\ImageMagick\LICENSE ..\..\install\*
      - name: Tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ImageMagick-${{steps.virtuals.outputs.vs}}-${{matrix.arch}}
          path: install
